In [1]:
 # Import the necessary modules
  # Bring each CSV into a separate data frame
  # Merge the first two datasets (2013 and 2014) on "Wrestler" so that no data is lost (should be 182 rows)
  # Rename our _x columns to "2013 Wins", "2013 Losses", and "2013 Draws"

# Rename our _y columns to "2014 Wins", "2014 Losses", and "2014 Draws"

  # Merge our newly combined dataframe with the 2015 dataframe
  # Rename "wins", "losses", and "draws" to "2015 Wins", "2015 Losses", and "2015 Draws"
  # Merge our newly combined dataframe with the 2016 dataframe

  # Rename "wins", "losses", and "draws" to "2016 Wins", "2016 Losses", and "2016 Draws"

In [3]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [6]:
data_2013_load = "Resources/WWE-Data-2013.csv"

In [8]:
data_2013_df = pd.read_csv(data_2013_load)
data_2013_df.head(15)

           Wrestler  Wins  Losses  Draws
0      Daniel Bryan   177      37      6
1      Dean Ambrose    70     134      4
2    Antonio Cesaro    80     126      1
3      Seth Rollins    50     150      4
4       Randy Orton   129      63      8
5      Roman Reigns    49     140      5
6            Ryback   103      88      3
7     Damien Sandow    39     147      3
8   Alberto Del Rio   126      53      4
9     Dolph Ziggler    62     117      1
10      Cody Rhodes    47     114      3
11     Jack Swagger    56      96      2
12    Kofi Kingston    66      79      4
13       Zack Ryder    66      80      0
14      Brodus Clay   100      44      1